import Link from "next/link";
import { ArrowUpRight, CalendarDays, Check, Compass, MapPin, MessageCircle, Phone, ShieldCheck } from "lucide-react";
import { site } from "@/data/site";
import { DepthImage } from "./depth-image";
import { SectionHeading } from "./section-heading";
import { ServiceCard } from "./service-card";
import { FAQ } from "./faq";

const whatsappUrl = () => `https://wa.me/${site.whatsapp}?text=${encodeURIComponent("Hello Brajwasi Events, I want to discuss an event.")}`;

export function HomeSections() {
  return <>
    <section className="hero"><div className="hero__ambient hero__ambient--one" /><div className="hero__ambient hero__ambient--two" /><div className="container hero__grid"><div className="hero__copy"><p className="eyebrow">{site.hero.eyebrow}</p><h1>{site.hero.title} <span>{site.hero.highlight}</span></h1><p className="hero__description">{site.hero.description}</p><div className="hero__actions"><Link className="button" href="/contact/">{site.hero.primaryCta}<ArrowUpRight size={17} aria-hidden="true" /></Link><Link className="button button--ghost" href="/services/">{site.hero.secondaryCta}</Link></div><div className="hero__micro"><span><MapPin size={14} aria-hidden="true" /> Vrindavan, Mathura</span><span><Compass size={14} aria-hidden="true" /> India & destination</span></div></div><div className="hero__visual"><DepthImage src={site.hero.image} alt="Elegant wedding event environment styled by Brajwasi Events" label="Designed to be remembered" priority /><div className="hero-float hero-float--top"><span className="hero-float__index">01</span><span>Spatial design</span></div><div className="hero-float hero-float--bottom"><CalendarDays size={17} aria-hidden="true" /><span>Concept to execution</span></div></div></div></section>
    <div className="service-strip"><div className="container service-strip__track">{site.focusAreas.map((item) => <span key={item}>{item}</span>)}</div></div>
    <section className="section section--intro"><div className="container split-intro"><div><p className="eyebrow">{site.intro.eyebrow}</p><h2>{site.intro.title}</h2></div><div className="split-intro__copy"><p>{site.intro.description}</p><Link className="text-link" href="/about/">Our approach <ArrowUpRight size={16} aria-hidden="true" /></Link></div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Signature services" title="Built around the occasion, not a template." description="Wedding decoration, corporate events, event management, temple floral styling and destination celebrations." /><div className="service-grid">{site.services.slice(0,4).map((service,index) => <ServiceCard key={service.slug} service={service} featured={index===0} />)}</div><div className="section-end-link"><Link className="button button--ghost" href="/services/">View all services <ArrowUpRight size={17} aria-hidden="true" /></Link></div></div></section>
    <section className="section section--dark"><div className="container dark-grid"><div className="dark-grid__visual"><DepthImage src={site.services[3].image} alt="Floral temple decoration concept" label="Phool Bangla" /></div><div className="dark-grid__copy"><p className="eyebrow">A distinct Braj signature</p><h2>Floral architecture for sacred spaces.</h2><p>Phool bangla is more than placing flowers. It is a temporary architecture of colour, rhythm and detail designed around the character of the mandir and the darshan experience.</p><div className="dark-list">{site.services[3].features.map((feature) => <div key={feature}><Check size={16} aria-hidden="true" /><span>{feature}</span></div>)}</div><Link className="button button--light" href="/services/phool-bangla-temple-decoration/">Explore phool bangla <ArrowUpRight size={17} aria-hidden="true" /></Link></div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Where we work" title="Rooted in Braj. Ready for the destination." description="Vrindavan, Mathura, Agra, Delhi, Noida and destination event locations across India." /><div className="location-grid">{site.locations.slice(0,5).map((location) => <Link className="location-card" href={`/locations/${location.slug}/`} key={location.slug}><DepthImage src={location.image} alt={`${location.name} event styling`} label={location.name} /><div className="location-card__body"><p className="card-kicker">{location.eyebrow}</p><h3>{location.name}</h3><span>{location.title}</span></div></Link>)}</div><div className="section-end-link"><Link className="text-link" href="/locations/">Explore service locations <ArrowUpRight size={16} aria-hidden="true" /></Link></div></div></section>
    <section className="section section--soft"><div className="container process-layout"><SectionHeading eyebrow="How it comes together" title="A calm process behind a high-impact setup." description="One visual direction, one execution rhythm, fewer moving pieces for you to manage." /><div className="process-grid">{site.process.map((step) => <div className="process-card" key={step.number}><span>{step.number}</span><h3>{step.title}</h3><p>{step.description}</p></div>)}</div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Selected visual language" title="2.5D presentation. Real-world event energy." description="Photography is treated like an object in space: layered, tilted and framed with depth." align="center" /><div className="gallery-preview">{site.gallery.slice(0,4).map((item) => <div className="gallery-tile" key={item.title}><DepthImage src={item.image} alt={item.title} label={item.category} /></div>)}</div><div className="section-end-link"><Link className="button button--ghost" href="/gallery/">Open gallery <ArrowUpRight size={17} aria-hidden="true" /></Link></div></div></section>
    <section className="section section--dark"><div className="container cta-panel"><div><p className="eyebrow">Start with the brief</p><h2>Tell us the date, place and feeling. We&apos;ll shape the direction.</h2></div><div className="cta-panel__actions"><a className="button button--light" href={`tel:+91${site.phone}`}><Phone size={17} aria-hidden="true" /> Call {site.phoneDisplay}</a><a className="button button--outline-light" href={whatsappUrl()} target="_blank" rel="noreferrer"><MessageCircle size={17} aria-hidden="true" /> WhatsApp brief</a></div></div></section>
    <section className="section"><div className="container trust-grid"><SectionHeading eyebrow="Why Brajwasi" title="Designed with detail. Delivered with discipline." description="We keep the visual language strong while staying practical about venue conditions, production and the guest journey." /><div className="trust-points"><div><ShieldCheck size={20} aria-hidden="true" /><span>One clear visual direction from concept to setup.</span></div><div><Compass size={20} aria-hidden="true" /><span>Venue-first planning that adapts to the actual space.</span></div><div><Check size={20} aria-hidden="true" /><span>Detailed coordination for decor and event execution.</span></div><div><MapPin size={20} aria-hidden="true" /><span>Vrindavan base with destination capability across India.</span></div></div></div></section>
    <section className="section section--soft"><div className="container"><SectionHeading eyebrow="Frequently asked" title="Useful answers before you start planning." align="center" /><FAQ /></div></section>
  </>;
}
