import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Check, MapPin, Phone } from "lucide-react";
import { site } from "@/data/site";
import { buildMetadata } from "@/lib/seo";
import { breadcrumbSchema, jsonLd } from "@/lib/schema";
import { DepthImage } from "@/components/depth-image";
export const dynamicParams = false;
export function generateStaticParams() { return site.locations.map((location) => ({ slug: location.slug })); }
const getLocation = (slug: string) => site.locations.find((location) => location.slug === slug);
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const location = getLocation(slug); if (!location) return {}; return buildMetadata({ title: `${location.name}: Wedding & Event Management`, description: location.description, path: `/locations/${location.slug}/` }); }
export default async function LocationPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const location = getLocation(slug); if (!location) return null; return <><section className="detail-hero"><div className="container detail-hero__grid"><div className="detail-hero__copy"><Link className="back-link" href="/locations/"><ArrowLeft size={15} aria-hidden="true" /> All locations</Link><p className="eyebrow">{location.eyebrow}</p><h1>{location.title}</h1><p>{location.description}</p><div className="detail-meta"><span><MapPin size={15} aria-hidden="true" /> {location.name}</span><span><Check size={15} aria-hidden="true" /> {location.services.join(" • ")}</span></div></div><DepthImage src={location.image} alt={`${location.name} event styling by ${site.name}`} label={location.name} priority /></div></section><section className="section"><div className="container detail-content"><div><p className="eyebrow">Plan your event</p><h2>Tell us what the place needs to feel like.</h2><p className="body-copy">Share the event type, approximate guest count, venue and date. We can then shape the relevant service combination and production direction.</p></div><div className="feature-list">{location.services.map((service) => { const item = site.services.find((s) => s.title === service); return item ? <Link key={service} className="feature-list__link" href={`/services/${item.slug}/`}><span>{service}</span><ArrowUpRight size={16} aria-hidden="true" /></Link> : null; })}</div></div></section><section className="section section--soft"><div className="container contact-mini"><div><p className="eyebrow">Brajwasi Events</p><h2>Based at {site.address}.</h2></div><div className="contact-mini__actions"><a className="button" href={`tel:+91${site.phone}`}><Phone size={17} aria-hidden="true" /> Call {site.phoneDisplay}</a><Link className="button button--ghost" href="/contact/">Request a quote <ArrowUpRight size={17} aria-hidden="true" /></Link></div></div></section><script type="application/ld+json" dangerouslySetInnerHTML={jsonLd(breadcrumbSchema([{name:site.name,path:"/"},{name:"Locations",path:"/locations/"},{name:location.name,path:`/locations/${location.slug}/`}]))} /></>; }
