import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Check, MapPin, Phone } from "lucide-react";
import { site } from "@/data/site";
import { buildMetadata } from "@/lib/seo";
import { breadcrumbSchema, jsonLd, serviceSchema } from "@/lib/schema";
import { DepthImage } from "@/components/depth-image";
export const dynamicParams = false;
export function generateStaticParams() { return site.services.map((service) => ({ slug: service.slug })); }
const getService = (slug: string) => site.services.find((service) => service.slug === slug);
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const service = getService(slug); if (!service) return {}; return buildMetadata({ title: service.seoTitle, description: service.seoDescription, path: `/services/${service.slug}/` }); }
export default async function ServicePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const service = getService(slug); if (!service) return null; return <><section className="detail-hero"><div className="container detail-hero__grid"><div className="detail-hero__copy"><Link className="back-link" href="/services/"><ArrowLeft size={15} aria-hidden="true" /> All services</Link><p className="eyebrow">{service.shortTitle}</p><h1>{service.title}</h1><p>{service.detail}</p><div className="detail-meta"><span><MapPin size={15} aria-hidden="true" /> Vrindavan • Mathura • Agra • Delhi • Noida</span><span><Check size={15} aria-hidden="true" /> India & select international projects</span></div></div><DepthImage src={service.image} alt={`${service.title} service`} label={service.shortTitle} priority /></div></section><section className="section"><div className="container detail-content"><div><p className="eyebrow">What&apos;s included</p><h2>A considered setup, not a checklist.</h2></div><div className="feature-list">{service.features.map((feature) => <div key={feature}><span className="feature-list__icon"><Check size={16} aria-hidden="true" /></span><span>{feature}</span></div>)}</div></div></section><section className="section section--dark"><div className="container cta-panel"><div><p className="eyebrow">Build your version</p><h2>Share your event date, venue and scale.</h2></div><div className="cta-panel__actions"><a className="button button--light" href={`tel:+91${site.phone}`}><Phone size={17} aria-hidden="true" /> Call {site.phoneDisplay}</a><Link className="button button--outline-light" href="/contact/">Start a brief <ArrowUpRight size={17} aria-hidden="true" /></Link></div></div></section><script type="application/ld+json" dangerouslySetInnerHTML={jsonLd([serviceSchema(service), breadcrumbSchema([{name:site.name,path:"/"},{name:"Services",path:"/services/"},{name:service.title,path:`/services/${service.slug}/`}])])} /></>; }
